### ISSUE TITLE
content_for plugin

### ISSUE THREAD

**Issue by rustygeldmacher** [ebello/jekyll-perf#4]
Just a question -- how does the content_for plugin included here work?

Thanks!

**Comment by ebello** [comment]
Hi, thanks for asking. The content_for block was added to get around a limitation in Jekyll that page content can only be placed into one area in a template. In a Jekyll template you can specify an area to place all your page content using `{{content}}`, but I wanted to be able to place page specific content in different places in the template. A good example might be page specific styles or scripts. In practice I use it like this in a template:

``` HTML
<body>
    <header>
        {% content_for header %}
    </header>
    <section>
        {{content}}
    </section>
    {% content_for scripts %}
</body>
```

Then a specific page might look like this:

``` HTML
---
layout: default
title: Page title
---

---content header
<nav>
<ul>
  <li><a href="#">Link 1</a></li>
  <li><a href="#">Link 2</a></li>
</ul>  
</nav>
---content header

<article>
  <p>Normal page content</p>
</article>
```

When the page gets parsed only the `<article>` will get placed in the `{{content}}` area, and the `<nav>` will get placed in the `{% content_for header %}` area. As long as the names match across the template and the page content block it'll be fine. Note that they are optional, for example this page doesn't have any specific scripts, so the scripts content_for will be empty. But, if it did you can add it similar to how the header is provided, just replace with the name specified in the template.

**Comment by rustygeldmacher** [comment]
Hi Ernie, thanks for the detailed explanation, but I'm having trouble getting this to work for me -- what version of Jekyll does this work with? Are there any other dependencies that I need? Thanks!

**Comment by rustygeldmacher** [comment]
Hi Ernie, I ended up solving this a slightly different way -- I packaged it into a gem called jekyll-contentblocks: https://github.com/rustygeldmacher/jekyll-contentblocks

The content blocks in the gem allow markdown and liquid tags inside them.

Thanks for your work here, which I used as inspiration for my plugin!

**Comment by ebello** [comment]
Rusty, this is fantastic! Sorry I didn't back to you sooner. Great work. I'll see if I can include your gem into Jekyll-S3 without too much trouble. Thanks a lot.

**Comment by ebello** [comment]
Got around to including this gem in a larger rework of the project: https://github.com/ebello/jekyll-perf/commit/ed2ebebff4d74a222349a6e56b88b0d21e48318d

Thanks again.
